### PR TITLE
Add auto-modhash support to browser mode

### PR DESCRIPTION
**Pull request by empyrical**
This PR is identical to the one I made in #144 but instead is a branch of the main repo this time.

The reason why it failed last time is the unit tests require a lot of environment variables that are set in the Travis CI settings for this repo and they don't seem to propagate down to forks.

### CODE REVIEW

**Comment by empyrical** [comment]
Oops, looks like I need to add another test

**Comment by trevorsenior** [comment]
Thanks for working on this. 

> The reason why it failed last time is the unit tests require a lot of environment variables that are set in the Travis CI settings for this repo and they don't seem to propagate down to forks.

Yeah, it's pretty involved / Travis CI is using a reddit account to test this. Not the best scenario but it works well enough. I wish it would propigate down to forks, but I guess it's to prevent abuse. Glad that the branch tests work alright.

Your changes are in version `3.3.0`

**Comment by empyrical** [comment]
Awesome, glad to see it get merged, thanks! :D

**Comment by empyrical** [comment]
@trevorsenior Looks like the package on NPM is missing the `build/` folder so it can't quite be required properly

**Comment by trevorsenior** [comment]
Shows how distant I am from this project. I've built it and threw it on `npm` version `3.3.1` & deprecated version `3.3.0`. Thanks for the catch.

**Comment by empyrical** [comment]
Seems to work great now, thanks!

**Pull request merged**
