### PR TITLE
Add support for browser cookies

### PR DESCRIPTION
**Pull request by empyrical**
This change adds the ability for Snoocore to take advantage of the cookies in the user's browser (for example, in a browser extension). Addresses my issue, #134.

Some details you might want to discuss:

 * I chose to set the default "oauth" url to be `json.reddit.com` when in cookie mode, because like `oauth.reddit.com`, all responses from that are guaranteed to be json.
 * The reddit documentation doesn't mention what to do regarding the `User-Agent` when you're in an environment where you can't set it, but Twitter's docs suggests using `X-User-Agent`. @honestbleeps made RES add the URL parameter `&app=res` to distinguish its requests from other reddit requests for the admins, that may be an alternative way to do it.
 * `useBrowserCookies` attempts to bypass the oauth stuff completely. I tried to do this while making the least amount of changes to your code - I hope I didn't make things too gross!
 * I didn't think of this until putting together this list - maybe you'd like there to be an error thrown when using `useBrowserCookies` in node?

### CODE REVIEW

**Comment by trevorsenior** [comment]
:+1: looks good, thanks! I'll test it this evening and throw it in `3.1.0`. 

* `json.reddit.com` is fine - I'll probably clean up some of the language in the code
* I'm a fan of `X-User-Agent` vs. the `&app=res`
* The code is pretty gross already, so no worries. Thanks for catching that spelling mistake :wink: 
* As for the error, I just threw in some checks to help prevent OAuth questions popping up all over the place. I wouldn't worry about the error check for this & will make it clear in the documentation that it's only for browser scripts that are injected into the reddit page (like RES).

**Comment by trevorsenior** [comment]
Unfortunately `json.reddit.com` will not work for this as it bumps into CORS issues. I sucessfully got it working by changing it back to `www.reddit.com`. You will have to take a look at the old reddit API to learn about endpoints that still work (cookie API) such as `/api/me.json` which are no longer listed in the current API:

https://web.archive.org/web/20140104011658/http://www.reddit.com/dev/api#GET_api_me.json

Will throw this in within the next hour. Everything else seems alright & working:

proof that it works in chrome console!

**Comment by empyrical** [comment]
I'm using it inside of the background script in chrome/firefox (not in the content script itself) and CORS isn't an issue there as it has access to all domains that you have added as a permission; also, it should work in a content script if you add json.reddit.com or *.reddit.com as a permission in your chrome manifest.json/firefox package.json

**Comment by honestbleeps** [comment]
a huge caveat though:

if you did www.reddit.com and not *.reddit.com, when you update your chrome extension with the new permission to enable json.reddit.com or *.reddit.com, it will be disabled and your users will get a big scary prompt about how the extension is "asking for permission to read and modify your data on *.reddit.com" or some such.

that can be a huge headache. even though users read nearly the same message on initial installation, they totally lose their minds when they see a similar message on update.

**Comment by empyrical** [comment]
That's definitely true, I've seen how the RES guys have it when they need to add another permission and it's painful. Perhaps then, json.reddit.com could just be a mention in the docs as something people can use if they'd like; I'm not sure how many people know about that subdomain

**Comment by trevorsenior** [comment]
@honestbleeps good to know. I haven't touched browser extensions for some time / never had a user base to worry about in terms of updating those extensions.

@empyrical I'm going to keep it `www.reddit.com` as the default, but feel free to use `json.reddit.com` / any other hidden subdomain and override that default.

```javascript
new Snoocore({
    userAgent: 'test test test',
    useBrowserCookies: true,
    serverOAuth: 'json.reddit.com'
});
``` 

This feels wrong though. I'll modify the names to:

```
serverOAuth -> apiServerUri
serverWWW -> authServerUri
```

in a future release, because that is actually what those servers are used for.

**Comment by trevorsenior** [comment]
Alright, everything is updated & pushed to `npm`

The version you will want to use is `3.1.1` ~ I went ahead and added in the new alias' for servers. If you want to use `json.reddit.com`:

```javascript
new Snoocore({
    userAgent: 'test test test',
    useBrowserCookies: true,
    apiServerUri: 'json.reddit.com'
});
```

Updated documentation:

* http://snoocore.readme.io/v3.0.0/docs/configuration-options#section-servers
* http://snoocore.readme.io/v3.0.0/docs/using-existing-browser-cookies
* http://snoocore.readme.io/v3.0.0/docs/configuration-options#section-use-browser-cookies

- - -

Thanks again for the PR @empyrical

**Comment by empyrical** [comment]
No problem, and thanks for the awesome library!

**Pull request merged**
